### ISSUE TITLE
Extra spaces

### ISSUE THREAD

**Issue by rfarouni** [padlocbio/padloc-db#2]
Hi @leightonpayne @JacksonLab ,

The `system.definition.shortcut` column will parse [incorrectly](https://github.com/padlocbio/padloc/blob/67fba39a104748ffaab605eff935ebc69d058d08/bin/padloc.R#L141) the four entries in the hmm_meta.txt file that have extra spaces around the bar separator 

![Screenshot from 2021-11-15 14-49-19](https://user-images.githubusercontent.com/9895004/141793118-2f7b8d90-3f72-479e-abe6-1ad3f9524467.png)

Best,
Rick

**Comment by JacksonLab** [comment]
Hi Rick,

Thanks for spotting this. I've updated hmm_meta.txt to remove the spaces. I also added a line in padloc.R that should remove any spaces when parsing `protein.name` and `system.definition.shortcut`

Cheers,

Simon
