### ISSUE TITLE
[Suggestion] Add the SiAgo system

### ISSUE THREAD

**Issue by apcamargo** [padlocbio/padloc-db#3]
SiAgo is an archaeal system that uses a prokaryotic Argonaute to mediate abortive infection ([reference](https://www.biorxiv.org/content/10.1101/2021.12.09.471704v1.full)).

I generated MSAs for the three components of this system using two iterations in PSI-BLAST (download [here](https://github.com/padlocbio/padloc-db/files/7720325/SiAgo.zip)).

**Comment by JacksonLab** [comment]
Thanks Antonio! We're definitely keen to add this system. I contacted one of the co-authors when the preprint came up on twitter and they're going to send the hmms used in the study. We'll include this in the next update.
Cheers,
Simon

**Comment by apcamargo** [comment]
That's great to hear, @JacksonLab! I didn't realize they had their own set of HMMs.

**Comment by JacksonLab** [comment]
Added to the Webserver and precomputed results. We'll push to padloc-db in the new year.
