### ISSUE TITLE
Question regarding the recently added systems

### ISSUE THREAD

**Issue by Dfvandenberg** [padlocbio/padloc-db#4]
Hi,

I was wondering when the pAgo and dXTPases were going to be added to the github.
I found them to be added in the server, but when I run it via the github version it doesn't find these systems.
Fyi I used GCF_003029685.1 (https://padloc.otago.ac.nz/padloc/refseq/20fe3797d79ccfe4184b86fb50db53e7458f90cb6a99429817fe5724b765d699) as a check, but didn't find the new systems.

With kind regards,
Daan

**Comment by JacksonLab** [comment]
Hi Daan,

We've loaded the new systems to the webserver and precomputed results. The server is usually ahead of the github database as we use that for testing and QC before assigning PLDC#s to the HMMs. There are a couple more things to complete before we push these to padloc-db, so we'll get to this in the new year. 

Cheers,

Simon

**Comment by apcamargo** [comment]
Hijacking this thread to ask a related question: are there plans to add type II R-M systems?

**Comment by JacksonLab** [comment]
Type II RM are in the next webserver update and will come out in padlocdb the following release.

**Comment by yogihooda** [comment]
The BREX system has also not been added to the padlocdb, it would be great to have that updated as with the webserver. Thanks.

**Comment by leightonpayne** [comment]
pAgo, dXTPases, BREX now added (PADLOC-DB v1.3.0), RM will be added in following release
