### ISSUE TITLE
Target coverage threshold

### ISSUE THREAD

**Issue by rfarouni** [padlocbio/padloc-db#6]
Hi,

It seems to me that the HMMs for the RT genes icity0039, icity0040 have a target coverage threshold  in the meta [file](https://github.com/padlocbio/padloc-db/blob/master/hmm_meta.txt#L1135) that is too high. I would set it to 0.3 so it would be easier to detect an RT in a fusion gene. I was experimenting with your thresholds and I discovered that I missed a well-known cas-rt fusion gene with the set threshold of 0.5. 

Rick,

**Comment by JacksonLab** [comment]
Hi Rick,

Thanks for raising this, appreciate feedback from users. I've made a note to update these cutoffs with the next db release (so the change carries over to the precomputed dataset on the webserver as well).

Cheers,

Simon
