### ISSUE TITLE
Add spbK

### ISSUE THREAD

**Issue by apcamargo** [padlocbio/padloc-db#7]
spbK is a ICE-encoded TIR-containing protein that protects B. subtilis from predation by the SPß phage.

https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1010065

I built an MSA (and an HMM) using PSI-BLAST (download link below). I used a strict coverage threshold (90%) to avoid adding other TIR-containg proteins to the MSA.

[spbK.zip](https://github.com/padlocbio/padloc-db/files/8101364/spbK.zip)

**Comment by JacksonLab** [comment]
Thanks for putting this together, we'll add to the next update.

Cheers,

Simon
