### ISSUE TITLE
PDLC02976 missing

### ISSUE THREAD

**Issue by apcamargo** [padlocbio/padloc-db#8]
`PDLC02976` is listed in [`hmm_meta.txt`](https://github.com/padlocbio/padloc-db/blob/master/hmm_meta.txt), but is not included in the database. Not sure if this is intentional, but as `PDLC02976` is not in the deprecated directory, I thought it would be better to report it.

**Comment by JacksonLab** [comment]
Thanks for reporting. We've tracked down the HMM and added back to the database.

Cheers,

Simon
